### ISSUE TITLE
Feature Request - Allow User to Specify Date Format

### ISSUE THREAD

**Issue by alphaDev23** [wrighter/ib-scripts#15]
The following is an idea.  Different trading platforms require different date formats which if included as a option, will simplify work flow.

**Comment by wrighter** [comment]
One little side effect of this change is the default format that pandas used to write the csv files expressed timezone offsets in "HH:MM" format instead of "HHMM". This means that this change will cause date formats to be different going forward, but overall it seems like an improvement so it's worth it in my opinion
